// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/v1/login.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Login_LoginFromEmail_FullMethodName  = "/goddess.api.v1.Login/LoginFromEmail"
	Login_LoginFromPhone_FullMethodName  = "/goddess.api.v1.Login/LoginFromPhone"
	Login_LoginFromOAuth2_FullMethodName = "/goddess.api.v1.Login/LoginFromOAuth2"
)

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginClient interface {
	LoginFromEmail(ctx context.Context, in *LoginFromEmailRequest, opts ...grpc.CallOption) (*LoginReply, error)
	LoginFromPhone(ctx context.Context, in *LoginFromPhoneRequest, opts ...grpc.CallOption) (*LoginReply, error)
	LoginFromOAuth2(ctx context.Context, in *LoginFromOAuth2Request, opts ...grpc.CallOption) (*LoginReply, error)
}

type loginClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginClient(cc grpc.ClientConnInterface) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) LoginFromEmail(ctx context.Context, in *LoginFromEmailRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, Login_LoginFromEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) LoginFromPhone(ctx context.Context, in *LoginFromPhoneRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, Login_LoginFromPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) LoginFromOAuth2(ctx context.Context, in *LoginFromOAuth2Request, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, Login_LoginFromOAuth2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
// All implementations must embed UnimplementedLoginServer
// for forward compatibility.
type LoginServer interface {
	LoginFromEmail(context.Context, *LoginFromEmailRequest) (*LoginReply, error)
	LoginFromPhone(context.Context, *LoginFromPhoneRequest) (*LoginReply, error)
	LoginFromOAuth2(context.Context, *LoginFromOAuth2Request) (*LoginReply, error)
	mustEmbedUnimplementedLoginServer()
}

// UnimplementedLoginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginServer struct{}

func (UnimplementedLoginServer) LoginFromEmail(context.Context, *LoginFromEmailRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginFromEmail not implemented")
}
func (UnimplementedLoginServer) LoginFromPhone(context.Context, *LoginFromPhoneRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginFromPhone not implemented")
}
func (UnimplementedLoginServer) LoginFromOAuth2(context.Context, *LoginFromOAuth2Request) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginFromOAuth2 not implemented")
}
func (UnimplementedLoginServer) mustEmbedUnimplementedLoginServer() {}
func (UnimplementedLoginServer) testEmbeddedByValue()               {}

// UnsafeLoginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServer will
// result in compilation errors.
type UnsafeLoginServer interface {
	mustEmbedUnimplementedLoginServer()
}

func RegisterLoginServer(s grpc.ServiceRegistrar, srv LoginServer) {
	// If the following call pancis, it indicates UnimplementedLoginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Login_ServiceDesc, srv)
}

func _Login_LoginFromEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginFromEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).LoginFromEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Login_LoginFromEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).LoginFromEmail(ctx, req.(*LoginFromEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_LoginFromPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginFromPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).LoginFromPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Login_LoginFromPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).LoginFromPhone(ctx, req.(*LoginFromPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_LoginFromOAuth2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginFromOAuth2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).LoginFromOAuth2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Login_LoginFromOAuth2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).LoginFromOAuth2(ctx, req.(*LoginFromOAuth2Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Login_ServiceDesc is the grpc.ServiceDesc for Login service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Login_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goddess.api.v1.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginFromEmail",
			Handler:    _Login_LoginFromEmail_Handler,
		},
		{
			MethodName: "LoginFromPhone",
			Handler:    _Login_LoginFromPhone_Handler,
		},
		{
			MethodName: "LoginFromOAuth2",
			Handler:    _Login_LoginFromOAuth2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/login.proto",
}
