// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/v1/member.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Member_InviteMemberFromEmail_FullMethodName = "/goddess.api.v1.Member/InviteMemberFromEmail"
	Member_InviteMemberFromPhone_FullMethodName = "/goddess.api.v1.Member/InviteMemberFromPhone"
	Member_TerminateMember_FullMethodName       = "/goddess.api.v1.Member/TerminateMember"
	Member_UpdateMemberStatus_FullMethodName    = "/goddess.api.v1.Member/UpdateMemberStatus"
	Member_GetMember_FullMethodName             = "/goddess.api.v1.Member/GetMember"
	Member_ListMember_FullMethodName            = "/goddess.api.v1.Member/ListMember"
	Member_SelectMember_FullMethodName          = "/goddess.api.v1.Member/SelectMember"
)

// MemberClient is the client API for Member service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemberClient interface {
	InviteMemberFromEmail(ctx context.Context, in *InviteMemberFromEmailRequest, opts ...grpc.CallOption) (*InviteMemberReply, error)
	InviteMemberFromPhone(ctx context.Context, in *InviteMemberFromPhoneRequest, opts ...grpc.CallOption) (*InviteMemberReply, error)
	TerminateMember(ctx context.Context, in *TerminateMemberRequest, opts ...grpc.CallOption) (*TerminateMemberReply, error)
	UpdateMemberStatus(ctx context.Context, in *UpdateMemberStatusRequest, opts ...grpc.CallOption) (*UpdateMemberStatusReply, error)
	GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*MemberItem, error)
	ListMember(ctx context.Context, in *ListMemberRequest, opts ...grpc.CallOption) (*ListMemberReply, error)
	SelectMember(ctx context.Context, in *SelectMemberRequest, opts ...grpc.CallOption) (*SelectMemberReply, error)
}

type memberClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberClient(cc grpc.ClientConnInterface) MemberClient {
	return &memberClient{cc}
}

func (c *memberClient) InviteMemberFromEmail(ctx context.Context, in *InviteMemberFromEmailRequest, opts ...grpc.CallOption) (*InviteMemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMemberReply)
	err := c.cc.Invoke(ctx, Member_InviteMemberFromEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) InviteMemberFromPhone(ctx context.Context, in *InviteMemberFromPhoneRequest, opts ...grpc.CallOption) (*InviteMemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMemberReply)
	err := c.cc.Invoke(ctx, Member_InviteMemberFromPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) TerminateMember(ctx context.Context, in *TerminateMemberRequest, opts ...grpc.CallOption) (*TerminateMemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateMemberReply)
	err := c.cc.Invoke(ctx, Member_TerminateMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) UpdateMemberStatus(ctx context.Context, in *UpdateMemberStatusRequest, opts ...grpc.CallOption) (*UpdateMemberStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMemberStatusReply)
	err := c.cc.Invoke(ctx, Member_UpdateMemberStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*MemberItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberItem)
	err := c.cc.Invoke(ctx, Member_GetMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) ListMember(ctx context.Context, in *ListMemberRequest, opts ...grpc.CallOption) (*ListMemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemberReply)
	err := c.cc.Invoke(ctx, Member_ListMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) SelectMember(ctx context.Context, in *SelectMemberRequest, opts ...grpc.CallOption) (*SelectMemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectMemberReply)
	err := c.cc.Invoke(ctx, Member_SelectMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServer is the server API for Member service.
// All implementations must embed UnimplementedMemberServer
// for forward compatibility.
type MemberServer interface {
	InviteMemberFromEmail(context.Context, *InviteMemberFromEmailRequest) (*InviteMemberReply, error)
	InviteMemberFromPhone(context.Context, *InviteMemberFromPhoneRequest) (*InviteMemberReply, error)
	TerminateMember(context.Context, *TerminateMemberRequest) (*TerminateMemberReply, error)
	UpdateMemberStatus(context.Context, *UpdateMemberStatusRequest) (*UpdateMemberStatusReply, error)
	GetMember(context.Context, *GetMemberRequest) (*MemberItem, error)
	ListMember(context.Context, *ListMemberRequest) (*ListMemberReply, error)
	SelectMember(context.Context, *SelectMemberRequest) (*SelectMemberReply, error)
	mustEmbedUnimplementedMemberServer()
}

// UnimplementedMemberServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemberServer struct{}

func (UnimplementedMemberServer) InviteMemberFromEmail(context.Context, *InviteMemberFromEmailRequest) (*InviteMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteMemberFromEmail not implemented")
}
func (UnimplementedMemberServer) InviteMemberFromPhone(context.Context, *InviteMemberFromPhoneRequest) (*InviteMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteMemberFromPhone not implemented")
}
func (UnimplementedMemberServer) TerminateMember(context.Context, *TerminateMemberRequest) (*TerminateMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateMember not implemented")
}
func (UnimplementedMemberServer) UpdateMemberStatus(context.Context, *UpdateMemberStatusRequest) (*UpdateMemberStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMemberStatus not implemented")
}
func (UnimplementedMemberServer) GetMember(context.Context, *GetMemberRequest) (*MemberItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMember not implemented")
}
func (UnimplementedMemberServer) ListMember(context.Context, *ListMemberRequest) (*ListMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMember not implemented")
}
func (UnimplementedMemberServer) SelectMember(context.Context, *SelectMemberRequest) (*SelectMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectMember not implemented")
}
func (UnimplementedMemberServer) mustEmbedUnimplementedMemberServer() {}
func (UnimplementedMemberServer) testEmbeddedByValue()                {}

// UnsafeMemberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberServer will
// result in compilation errors.
type UnsafeMemberServer interface {
	mustEmbedUnimplementedMemberServer()
}

func RegisterMemberServer(s grpc.ServiceRegistrar, srv MemberServer) {
	// If the following call pancis, it indicates UnimplementedMemberServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Member_ServiceDesc, srv)
}

func _Member_InviteMemberFromEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMemberFromEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).InviteMemberFromEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_InviteMemberFromEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).InviteMemberFromEmail(ctx, req.(*InviteMemberFromEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_InviteMemberFromPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMemberFromPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).InviteMemberFromPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_InviteMemberFromPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).InviteMemberFromPhone(ctx, req.(*InviteMemberFromPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_TerminateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).TerminateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_TerminateMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).TerminateMember(ctx, req.(*TerminateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_UpdateMemberStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).UpdateMemberStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_UpdateMemberStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).UpdateMemberStatus(ctx, req.(*UpdateMemberStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_GetMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).GetMember(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_ListMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).ListMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_ListMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).ListMember(ctx, req.(*ListMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_SelectMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).SelectMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Member_SelectMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).SelectMember(ctx, req.(*SelectMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Member_ServiceDesc is the grpc.ServiceDesc for Member service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Member_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goddess.api.v1.Member",
	HandlerType: (*MemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InviteMemberFromEmail",
			Handler:    _Member_InviteMemberFromEmail_Handler,
		},
		{
			MethodName: "InviteMemberFromPhone",
			Handler:    _Member_InviteMemberFromPhone_Handler,
		},
		{
			MethodName: "TerminateMember",
			Handler:    _Member_TerminateMember_Handler,
		},
		{
			MethodName: "UpdateMemberStatus",
			Handler:    _Member_UpdateMemberStatus_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _Member_GetMember_Handler,
		},
		{
			MethodName: "ListMember",
			Handler:    _Member_ListMember_Handler,
		},
		{
			MethodName: "SelectMember",
			Handler:    _Member_SelectMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/member.proto",
}
