// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: enum/enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment int32

const (
	Environment_UNKNOWN Environment = 0
	Environment_DEV     Environment = 1
	Environment_TEST    Environment = 2
	Environment_PREVIEW Environment = 3
	Environment_PROD    Environment = 4
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEV",
		2: "TEST",
		3: "PREVIEW",
		4: "PROD",
	}
	Environment_value = map[string]int32{
		"UNKNOWN": 0,
		"DEV":     1,
		"TEST":    2,
		"PREVIEW": 3,
		"PROD":    4,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[0].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[0]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{0}
}

type GlobalStatus int32

const (
	GlobalStatus_GlobalStatus_UNKNOWN GlobalStatus = 0
	GlobalStatus_ENABLED              GlobalStatus = 1
	GlobalStatus_DISABLED             GlobalStatus = 2
)

// Enum value maps for GlobalStatus.
var (
	GlobalStatus_name = map[int32]string{
		0: "GlobalStatus_UNKNOWN",
		1: "ENABLED",
		2: "DISABLED",
	}
	GlobalStatus_value = map[string]int32{
		"GlobalStatus_UNKNOWN": 0,
		"ENABLED":              1,
		"DISABLED":             2,
	}
)

func (x GlobalStatus) Enum() *GlobalStatus {
	p := new(GlobalStatus)
	*p = x
	return p
}

func (x GlobalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[1].Descriptor()
}

func (GlobalStatus) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[1]
}

func (x GlobalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalStatus.Descriptor instead.
func (GlobalStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{1}
}

type UserStatus int32

const (
	UserStatus_UserStatus_UNKNOWN UserStatus = 0
	UserStatus_VALID              UserStatus = 1
	UserStatus_FORBIDDEN          UserStatus = 2
	UserStatus_WRITTEN_OFF        UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UserStatus_UNKNOWN",
		1: "VALID",
		2: "FORBIDDEN",
		3: "WRITTEN_OFF",
	}
	UserStatus_value = map[string]int32{
		"UserStatus_UNKNOWN": 0,
		"VALID":              1,
		"FORBIDDEN":          2,
		"WRITTEN_OFF":        3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[2].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[2]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{2}
}

type MemberStatus int32

const (
	MemberStatus_MemberStatus_UNKNOWN MemberStatus = 0
	MemberStatus_ON_JOB               MemberStatus = 1
	MemberStatus_BAN                  MemberStatus = 2
	MemberStatus_WAITING_JOIN         MemberStatus = 3
	MemberStatus_TERMINATED           MemberStatus = 4
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "MemberStatus_UNKNOWN",
		1: "ON_JOB",
		2: "BAN",
		3: "WAITING_JOIN",
		4: "TERMINATED",
	}
	MemberStatus_value = map[string]int32{
		"MemberStatus_UNKNOWN": 0,
		"ON_JOB":               1,
		"BAN":                  2,
		"WAITING_JOIN":         3,
		"TERMINATED":           4,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[3].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[3]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{3}
}

var File_enum_enum_proto protoreflect.FileDescriptor

var file_enum_enum_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x67, 0x6f, 0x64, 0x64, 0x65, 0x73, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2a,
	0x44, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44,
	0x45, 0x56, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x50, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x52, 0x4f, 0x44, 0x10, 0x04, 0x2a, 0x43, 0x0a, 0x0c, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x14, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x4f, 0x0a, 0x0a, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x46,
	0x4f, 0x52, 0x42, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x52,
	0x49, 0x54, 0x54, 0x45, 0x4e, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x03, 0x2a, 0x5f, 0x0a, 0x0c, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x14, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x5f, 0x4a, 0x4f, 0x42, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x41,
	0x49, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a,
	0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x44, 0x10, 0x04, 0x42, 0x39, 0x0a, 0x0c,
	0x67, 0x6f, 0x64, 0x64, 0x65, 0x73, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x50, 0x01, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x64, 0x65, 0x2d,
	0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x2f, 0x67, 0x6f, 0x64, 0x64, 0x65, 0x73, 0x73, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_enum_proto_rawDescOnce sync.Once
	file_enum_enum_proto_rawDescData = file_enum_enum_proto_rawDesc
)

func file_enum_enum_proto_rawDescGZIP() []byte {
	file_enum_enum_proto_rawDescOnce.Do(func() {
		file_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_enum_proto_rawDescData)
	})
	return file_enum_enum_proto_rawDescData
}

var file_enum_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_enum_enum_proto_goTypes = []any{
	(Environment)(0),  // 0: goddess.enum.Environment
	(GlobalStatus)(0), // 1: goddess.enum.GlobalStatus
	(UserStatus)(0),   // 2: goddess.enum.UserStatus
	(MemberStatus)(0), // 3: goddess.enum.MemberStatus
}
var file_enum_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_enum_proto_init() }
func file_enum_enum_proto_init() {
	if File_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_enum_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_enum_proto_goTypes,
		DependencyIndexes: file_enum_enum_proto_depIdxs,
		EnumInfos:         file_enum_enum_proto_enumTypes,
	}.Build()
	File_enum_enum_proto = out.File
	file_enum_enum_proto_rawDesc = nil
	file_enum_enum_proto_goTypes = nil
	file_enum_enum_proto_depIdxs = nil
}
